version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: password
    command: server /data --console-address ":9001"

  #  consumer:
  #    image: for-noru/consumer/scrape-place:latest
  #    environment:
  #      DB_HOST: 'postgres'
  #      DB_NAME: ${DB_NAME}
  #      REDIS_HOST: 'redis'
  #      REDIS_PORT: '6379'
  #    deploy:
  #      replicas: 1

  redis:
    image: redis:6.0.5
    ports:
      - '6379:6379'

  es01:
    image: elasticsearch:8.4.3
    ports:
      - '9200:9200'
      - '9300:9300'
    #    volumes:
    #      - es-volume:/usr/share/elasticsearch/data
    environment:
      - 'node.name=es01'
      - 'cluster.name=for-noru'
      - 'bootstrap.memory_lock=true'
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'xpack.security.enabled=false'
      - 'xpack.security.enrollment.enabled=false'
      - 'xpack.security.http.ssl.enabled=false'
      - 'xpack.security.transport.ssl.enabled=false'

  kibana:
    image: kibana:8.4.3
    depends_on:
      - es01
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    ports:
      - '5601:5601'

  mongo:
    image: mongo
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
