version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: password
    command: server /data --console-address ":9001"

  consumer:
    image: for-noru/consumer/scrape-place:latest
    environment:
      DB_HOST: 'postgres'
      DB_NAME: ${DB_NAME}
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
    deploy:
      replicas: 1

  redis:
    image: redis:6.0.5
    ports:
      - '6379:6379'
